title: AP Computer Science A
description: We will use GitHub to collaborate on projects.
template:
  repo: ap-computer-science-a-template
  name: ap-computer-science-a
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
